#!/usr/bin/env bash
set -e

cd src/images/sponsors/normal
rm -rf ../tint/ && mkdir ../tint/
for f in *
do
  yarn sharp --quality 100 --lossless tint $1 -i $f -o ../tmp/$f
  yarn sharp --quality 100 --lossless gamma 1 2 -i ../tmp/$f -o ../tint/$f
  # convert $f -colorspace gray -fill $1 -colorize 70 ../tint/$f
done
