name: deploy-event

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
        check-latest: true

    # github.event.pusher.name, github.event.pusher.email, actions@github.com
    - name: setup git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: install dependencies
      run: yarn install

    - name: deploy
      run: yarn run deploy-event
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
